---
language: node_js
node_js:
  - "lts/*"

sudo: required

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      
git:
  depth: 10

services:
  - mongodb

before_install:
  - git --version
  - mongod --version
  - npm install -g grunt-cli

install:
  - npm config set spin false
  - npm install
  - grunt build:prod

matrix:
  fast_finish: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/984c2f87fa167719344b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
